### ISSUE TITLE
--create-big-image ignores render settings

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#10]
It seems that --create-big-image only cares about what world files exist and then renders according to that instead of the render settings.

Example: I have a world with region files from -5 to 5 (in both X and Z). Asking it to render from -1028 to 1028 in both direction creates a big.png that 3,584px × 4,096px large. 

So first of all, the file should be much smaller if it would be rendering only the chunks bounding the +-1028 blocks (-3 to 2 instead of -5 to 5). The tiles.html does the same mistake by the way, but at least it contains the full block area assigned in the render command line. 

Second of all the big.png cuts off the right border of the image as it does not include the full width if the tiles rendered. 

Looking at the code at https://github.com/Minecraft-Technik-Wiki/BlockMap/blob/master/BlockMap-standalone/src/main/java/de/piegames/blockmap/standalone/PostProcessing.java#L98, it anyhow seems as if the RenderSettings are not a part of calculating the affected areas at all. Instead, all the dimensions for the image are taken from the availability of world files, not from the desired settings.

**Comment by piegamesde** [comment]
You are totally right. I forgot to add bounds checks to the command line, so all region files are rendered, even if all pixels are out of range. I'll change this soon.

**Comment by uncovery** [comment]
Can I help with something here? You are clearly much more of a pro in this than me, so I am afraid of submitting stuff that you'll have to re-write later anyhow...

**Comment by piegamesde** [comment]
I already redid some things that still need to be pushed. I'd appreciate your help on testing this (once it's pushed), since I do not really use these features at the moment.

**Comment by uncovery** [comment]
Happy to help there.

**Comment by uncovery** [comment]
Sorry to bug you, any update on this? The sign-on process on my server is somewhat crippled without a this functionality... It would be great to have a time horizon on this so I can either wait for it or work on a temporary workaround. Thanks!

**Comment by uncovery** [comment]
ok the program seems to react properly to the command now, some weird stuff is still happening, will open separate issue.
