### ISSUE TITLE
Using small values for --min-X etc causes weird issues in the tiles.html rendering

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#14]
## Environment info

- **BlockMap version**: `1.2.0`
- **Java version**: `openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)`
- **Operating system**: `Linux 3.10.0-862.2.3.el7.x86_64 #1 SMP Wed May 9 18:05:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux` 

## Description

using small coordinates (smaller than a chunk) creates weird results.
the big.png seems to be ok.

## Steps to reproduce

1. I am using a command line such as 

`java -jar BlockMap.jar render ./world/region --create-big-image --min-X=-4 --max-X=3 --min-Z=-4 --max-Z=3 -o ./target/png --create-tile-html`
2. look at the result
3. ...

### Actual result
It renders the given coordinates for every chunk in the affected regions, then assembles all the half-rendered chunks in all actually affected regions into a new image

### Expected result:
it should render the coordinates as expected only.

## Screenshots
tiles.html looks like this:
![this is the full tiles.html](https://user-images.githubusercontent.com/583808/51452051-5241cf80-1d73-11e9-870c-15a1210a670d.jpg)

**Comment by piegamesde** [comment]
How urgent is this issue to you?

**Comment by uncovery** [comment]
Not at all. I was just stumbling on this by accident and thought I'd let you know.

**Comment by piegamesde** [comment]
Thanks. I'm working on some changes that will generate more data while rendering that might help debugging, so I'll wait for that unless someone wants this fixed urgently.

**Comment by piegamesde** [comment]
Can you still reproduce this on newer versions?
