### ISSUE TITLE
Launch instructions are not clear for running from source project on Mac

### ISSUE THREAD

**Issue by rkiddy** [Minecraft-Technik-Wiki/BlockMap#19]
## Environment info
Mac OS 10.13.6 on Macbook Air.
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
$
```

## Description
Launch instructions are not clear for running from source project on Mac.

## Steps to reproduce

The README says "java -jar BlockMap-1.1.1.jar" will launch the app.

```
$ find * -name Block\*jar
BlockMap-core/build/libs/BlockMap-core-1.1.2.jar
BlockMap-core/build/libs/BlockMap-core-1.2.0.jar
BlockMap-gui/build/libs/BlockMap-gui-1.1.2.jar
BlockMap-gui/build/libs/BlockMap-gui-1.2.0.jar
BlockMap-internal/build/libs/BlockMap-internal-1.1.2.jar
BlockMap-standalone/build/libs/BlockMap-standalone-1.1.2.jar
$
```

Which one of these am I supposed to launch with? The way I have found that will work is to use "gradle run". If there is a java command line that will launch it, please say.

At the least, updating the instructions to refer to the current version of the jar shows that someone has checked this at least once. :-)

**Comment by piegamesde** [comment]
The usage instructions talk about the downloaded release from GitHub, even if it works with self-built releases using `./gradlew github`.

All except `BlockMap-internal.jar` are valid jar files. `BlockMap-core.jar` and `BlockMap-gui.jar` are libraries meant to be used from other applications (even they haven't been officially released yet), while `BlockMap-standalone.jar` is the standalone application you can run.

Thank you for the feedback, I'll update the readme.
