### ISSUE TITLE
Jar file never finishes downloading

### ISSUE THREAD

**Issue by apereason** [Minecraft-Technik-Wiki/BlockMap#25]
This isn't really related to the program but I can't download the jar file, chrome has the file about to be downloaded but something about it makes it unable to complete. I know that this file is the issue and it's not an issue with my computer because I tried downloading other jar files and they work fine. please help!

**Comment by piegamesde** [comment]
- Which OS do you have?
- Have you tried a different browser or dedicated downloading tools?
- Have you checked your antivirus software?
- Have you tried downloading it on another computer?
- Have you tried downloading an older release?

If all this does not work, you could try to build the release yourself.
