### ISSUE TITLE
tiles.html does not render properly

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#3]
it seems to render only on (the last) tile.

**Comment by piegamesde** [comment]
Please provide a way to reproduce this to give me a chance to fix it.

**Comment by piegamesde** [comment]
I updated a lot of things internally, so please try running gradle again: `gradle beforeCommit` will generate all resources (`gradle regenerate`) and run all the tests. I am going to upload a lot of documentation about how to use this and how to contribute (hopefully) soon.

**Comment by uncovery** [comment]
ok, this is fixed with the latest release.
