### ISSUE TITLE
Custom Color Map compiled, but not usable

### ISSUE THREAD

**Issue by gobo7793** [Minecraft-Technik-Wiki/BlockMap#37]
## Environment info

- **BlockMap version**: 1.6.1
- **Java version**: openjdk version "12.0.2" 2019-07-16
- **Operating system**: Debian

## Description
I've made for my server a new, custom color map to generate only rails on the map (for own further processing). I've added in the `block-color-instructions-1_15.json` a new color map `rails` and it compiles successfully. But with the current 1.6.1 (and as I can see in older logs in 1.6.0) the custom color map doesn't know the custom color map. In the `BlockMap-core/build/resources/main` dir I find the compiled color map `block-colors-rails-1_15.json`. And it worked on older versions.

## Steps to reproduce
1. Compile the branch `railmap` on my fork, I use `./gradlew regenerate && ./gradlew release && cp BlockMap-cli/build/libs/fat/BlockMap-cli-1.6.1.jar .`
2. execute `java -jar BlockMap-cli-1.6.1.jar render --lazy --create-big-image --create-tile-html --color-map RAILS --shader=FLAT --max-X=5000 --max-Z=5000 --min-X=-5000 --min-Z=-5000 -o <outputdir> <regionfiledir>`

### Actual result
Blockmap displays:
```
Invalid value for option '--color-map': expected one of [DEFAULT, OCEAN_GROUND, NO_FOLIAGE, CAVES, X_RAY] (case-sensitive) but was 'RAILS'
Usage: blockmap render [-hlp] [--create-big-image] [--create-tile-html] [-c=
                       {DEFAULT|CAVES|NO_FOLIAGE|OCEAN_GROUND|RAILS}] [-d=
                       {OVERWORLD|NETHER|END}] [--max-X=<maxX>]
                       [--max-Y=<maxY>] [--max-Z=<maxZ>] [--min-X=<minX>]
                       [--min-Y=<minY>] [--min-Z=<minZ>] [-o=<FOLDER>] [-s=
                       {FLAT|RELIEF|BIOMES|HEIGHTMAP}] INPUT
...
```

**Comment by piegamesde** [comment]
You need to "register" the color map in [`InternalColorMap`](https://github.com/gobo7793/BlockMap/blob/railmap/BlockMap-core/src/main/java/de/piegames/blockmap/color/BlockColorMap.java#L44) so the command line parser will know about it. You did that in your [original commit](https://github.com/gobo7793/BlockMap/commit/a6aa4e9756ce98a1b026d8236d2431cfa933a75f), but it apparently got lost during a merge (probably when I added the X-Ray map).

If you create a pull request with you changes, I'll be happy to incorporate and maintain them for future versions.

**Comment by piegamesde** [comment]
Thank you.
