### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by 3Domse3** [Minecraft-Technik-Wiki/BlockMap#39]
Error: A JNI error has occured, please check your installation and try again.

**Comment by piegamesde** [comment]
Please provide more information about your system and what you did so that I have a chance to understand the issue.

**Comment by 3Domse3** [comment]
I downloaded BlockMap-cli-1.6.2.jar and double clicked it. My system is Win10 with Java 1.8.0_241

**Comment by piegamesde** [comment]
Please run BlockMap from the command line as explained in the README. Maybe this will print more information.

**Comment by teolicht** [comment]
I have the same issue, tried running from the command line: "Error: Unable to access jarfile BlockMap-cli-1.6.2.jar"
