### ISSUE TITLE
Ambiguous error message

### ISSUE THREAD

**Issue by ComputerJock** [Minecraft-Technik-Wiki/BlockMap#57]
I loaded a 1.12 world. I got tons of messages:

20-08-02 15:39:56 WARN  RegionRenderer [130] - Skipping chunk because it is too old

Does it mean that the minecraft version of the world is too old (not supported)? Or does it mean that some timestamp on a chunk is too long in the past? If the latter, is there a way to ignore the error and render the chunk anyway?

**Comment by piegamesde** [comment]
Let's look at the code:

```java
if (version < MinecraftVersion.MC_1_13.minVersion) {
	log.warn("Skipping chunk because it is too old");
	metadata.put(chunkPos, new ChunkMetadataVersion(chunkPos, "This chunk was written from Minecraft <1.13, which is not supported", version));
	continue;
}
```

1. The error message could be better, I'll change this
2. A different error message is written to the metadata for that chunk, that explains it fairly well. When viewing skipped chunks in the GUI, there should be a pop-up that explains all the details.

**Comment by ComputerJock** [comment]
Thanks for the explanation. 
Perhaps a message when the world is selected saying 'minecraft version xxx is not supported' would be helpful.

**Comment by ComputerJock** [comment]
comment is above

**Comment by piegamesde** [comment]
> Perhaps a message when the world is selected saying 'minecraft version xxx is not supported' would be helpful.

The problem with this is that the Minecraft version is not some attribute to a world, but instead to each individual chunk. So sadly, this is not trivially possible
