### ISSUE TITLE
Symlinks were uploaded to Github as a file instead of a folder

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#6]
https://github.com/Minecraft-Technik-Wiki/BlockMap/blob/master/BlockMap-internal/src/main/generated-resources

this should be a folder.

**Comment by uncovery** [comment]
Same in all others ./src folders btw.

**Comment by piegamesde** [comment]
This is strange. The normal behavior should be that the broken symlink folder just gets ignored until it's not broken anymore. If you create the target folders manually, does this help?

    BlockMap-internal/build/generated-resources/internal-main
    BlockMap-internal/build/generated-resources/internal-test
    BlockMap-internal/build/generated-resources/core-main
    BlockMap-internal/build/generated-resources/gui-main
    BlockMap-internal/build/generated-resources/standalone-main
    BlockMap-internal/build/generated-resources/other

If so, I'll try to create a Gradle task that will mkdir those folders before compiling.

**Comment by uncovery** [comment]
well compile does not complain anymore if I manually create the generated-resources folders.

**Comment by uncovery** [comment]
Oh I misread the above. Let me trythis.

**Comment by uncovery** [comment]
Ok, tried that now, netbeans complains the instant you open the project. You have to create them all to get it to load without error. Even it it tried, it cannot even create those folders since a file with the same name already exists.

**Comment by piegamesde** [comment]
Apparently, Eclipse does too. I now removed the symlinks so `gradle regenerate eclipse` should fix everything.

**Comment by uncovery** [comment]
Can confirm, this is fixed now. Thanks!
