### ISSUE TITLE
Cannot read field "pins" because "helper" is null

### ISSUE THREAD

**Issue by uncovery** [Minecraft-Technik-Wiki/BlockMap#61]
## Environment info

- **BlockMap version**: `2.2.1`
- **Java version**: `"16.0.1" 2021-04-20`
- **Operating system**: `CENTOS Linux aimba 3.10.0-1127.19.1.el7.x86_64 #1 SMP Tue Aug 25 17:23:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

## Description
On one among several worlds, I am getting the following error:

```
ava.lang.NullPointerException: Cannot read field "pins" because "helper" is null
	at de.piegames.blockmap.world.RegionFolder$SavedRegionFolder.<init>(RegionFolder.java:293)
	at de.piegames.blockmap.world.RegionFolder$LocalRegionFolder.<init>(RegionFolder.java:355)
	at de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.<init>(RegionFolder.java:442)
	at de.piegames.blockmap.world.RegionFolder$CachedRegionFolder.create(RegionFolder.java:551)
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:236)
	at de.piegames.blockmap.standalone.CommandLineMain$CommandRender.call(CommandLineMain.java:113)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at de.piegames.blockmap.standalone.CommandLineMain.mainWithoutQuit(CommandLineMain.java:399)
	at de.piegames.blockmap.standalone.CommandLineMain.main(CommandLineMain.java:403)
```

## Steps to reproduce
I cannot instruct how to reproduce without uploading the whole world somewhere. Is there a chance to make a test for "helper" being null in the code and outputting which file is making trouble?

I tried to compile it myself but my Java skills are close to zero so I could not get it done. Compiling works but running throws this here:
```
java.lang.IllegalArgumentException: Did not find internal color map default
        at de.piegames.blockmap.color.BlockColorMap.loadInternal(BlockColorMap.java:348)
.....
```

**Comment by saibotk** [comment]
Did you compile it with our gradle tasks? 

Because besides compiling the code, there is also a task that downloads and regenerates the colormaps from the minecraft files.

**Comment by piegamesde** [comment]
Yes, if you want to run it yourself see https://github.com/Minecraft-Technik-Wiki/BlockMap#run-it . Essentially, you should run `./gradlew regenerate` and then it should work.


For reproduction, it'd be cool if you found a small example world that fails. But more importantly, please post the commands you are running that give you this result. Together with the stack trace, this should hopefully be enough for me figuring out what's going wrong.

**Comment by uncovery** [comment]
The command I am using is this:

/etc/alternatives/jre_16/bin/java -jar /folder/BlockMap-cli-2.2.1.jar render -f /folder/kingdom --create-big-image --min-X=-3264 --max-X=3264 --min-Z=-3264 --max-Z=3264 -o /folder/png --create-tile-html

**Comment by uncovery** [comment]
regenerate works. but then when I do the next one it fails.

```
gradlew :BlockMap-cli:run

> Configure project :BlockMap-gui
Project :BlockMap-gui => no module-info.java found

> Configure project :BlockMap-internal
Project :BlockMap-internal => no module-info.java found

> Task :BlockMap-cli:run FAILED
Missing required subcommand
Usage: blockmap [-hvV] COMMAND
  -h, --help      Print this help message and exit
  -v, --verbose   Be chatty
  -V, --version   Print version information and exit.
Commands:
  render       Render a folder containing region files to another folder
                 through the command line interface
  render-many  Render multiple worlds using a configuration file for usage in
                 servers

This is the command line interface of blockmap. To access the GUI (if
installed), run `blockmap-gui`.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':BlockMap-cli:run'.
> Process 'command 'C:\Program Files\Java\jdk-11\bin\java.exe'' finished with non-zero exit value 2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1s
6 actionable tasks: 4 executed, 2 up-to-date
```

**Comment by piegamesde** [comment]
That already looks promising. You can now pass command line arguments to the application. Doing so through Gradle is a bit unweildy because of potential escaping issues: `./gradlew :BlockMap-cli:run --args="render -f /folder/kingdom --create-big-image --min-X=-3264 --max-X=3264 --min-Z=-3264 --max-Z=3264 -o /folder/png --create-tile-html"`

-----

Regarding the issue, there should be a `rendered.json.gz` file in your output folder. It seems to be broken, please send me its content. You may also try deleting it and see if it helps.

**Comment by piegamesde** [comment]
Things are starting to get really weird. The application should create a `/folder/png` output folder and a `rendered.json.gz` in it. If you already run the command previously, the one already existing should be used instead.

Please try running in a clean output directory, just to make sure no corrupt files are causing this. After that `/folder/png/rendered.json.gz` should definitely exist as the error happens later, and the unzipped content should be `{regions:[]}`.

**Comment by uncovery** [comment]
Ah ok, I thought that .gz is a part of the compile output, not the run. I'll check that and get back to you.

**Comment by uncovery** [comment]
ok so....

1) If I run the latest version under java 16, the rendered.json.gz from the initial error report is empty. 
2) Making the map on Java 11 on windows works, the rendered.json.gz is created, but I assume you don't need that in this case, anyhow the text file in there is huge (18MB).
3) I am trying to compile under Java 11 now a ever so slightly changed version (where I add some more debug output to test running later under Java 16) with the instructions from the wiki (gradlew release) but get the following (after having run a "regenerate" sucessfully) 

```
gradlew release

> Configure project :BlockMap-gui
Project :BlockMap-gui => no module-info.java found

> Configure project :BlockMap-internal
Project :BlockMap-internal => no module-info.java found

> Configure project :BlockMap:BlockMap-gui
Project :BlockMap-gui => no module-info.java found

> Configure project :BlockMap:BlockMap-internal
Project :BlockMap-internal => no module-info.java found

> Task :BlockMap:BlockMap-internal:test FAILED

de.piegames.blockmap.ColorMapTest > initializationError FAILED
    java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
```

and repeating... 

Not sure where I should get/include/place this org/hamcrest/SelfDescribing

**Comment by piegamesde** [comment]
Yes, thank you. To be honest, I'm astonished that an empty file serializes to `null` instead of throwing a `DeserializationException` for invalid JSON.
