### ISSUE TITLE
im having a problem getting the .jar to load at all

### ISSUE THREAD

**Issue by dust5543** [Minecraft-Technik-Wiki/BlockMap#78]
## Environment info
- **BlockMap version BlockMap-cli-2.4.1
- **Java version**: `java -version` 18 also installed the latest jdk and also adoptopenjdk
- **Operating system**: win10

## Description
try to run the BlockMap-cli-2.4.1.jar but nothing happens iv tried to open as and pick java and jdk and nothing happens

**Comment by piegamesde** [comment]
The CLI jar file is supposed to be run from a command line interface. Clicking on the file is not supposed to do anything. You probably want to run BlockMap-gui-2.4.1-windows.jar instead. (Also note that I'd previously forgotten to upload the Windows build to the release, so you hadn't just overlooked it.)
